config/routes.rb
Rails.application.routes.draw do
  use_doorkeeper do
    skip_controllers :authorizations, :applications, :authorized_applications
  end
  # devise_for :users
  namespace :api do
    post "login"  => "session#create"
    delete "logout" => "session#destroy"
    resources :movies do
      collection do
        put 'reaction_movie'
      end
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :movie_users
  has_many :users, through: :movie_users
end

app/models/movie_user.rb
class MovieUser < ApplicationRecord
  belongs_to :movie
  belongs_to :user

  enum type_reaction: {
    like: 'like',
    dislike: 'dislike'
  }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :movie_users
  has_many :movies, through: :movie_users
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :email, format: URI::MailTo::EMAIL_REGEXP

  # the authenticate method from devise documentation
  def self.authenticate(email, password)
    user = User.find_for_authentication(email: email)
    user&.valid_password?(password) ? user : nil
  end

  def check_status(movie_id)
    user_reaction = movie_users.where(movie_id: movie_id).last
    return 'unset' if user_reaction.blank?
    user_reaction.type_reaction
  end
end

app/controllers/api/application_controller.rb
class Api::ApplicationController < ActionController::API
  before_action :doorkeeper_authorize!

  private
  def current_user
    Rails.logger.warn("===== #{doorkeeper_token.inspect} ========")
    @current_user ||= User.find_by(id: doorkeeper_token[:resource_owner_id]) if doorkeeper_token.present?
  end
end

app/controllers/api/movies_controller.rb
class Api::MoviesController < Api::ApplicationController
  skip_before_action :doorkeeper_authorize!, only: %i[ index ]

  # GET /movies or /movies.json
  def index
    @movies = Movie.all
    render :json => @movies, each_serializer: MovieSerializer, status: 200
  end

  def show
    render json: { result: @movie }, status: 200
  end

  def create
    command = Movies::SharedMovie.call(params[:video_url], current_user)
    render json: { result: MovieSerializer.new(command.result, scope: current_user) }, status: 200
  end

  def reaction_movie
    command = Movies::ReactionMovie.call(movie_params, current_user)
    render json: { result: MovieSerializer.new(command.result, scope: current_user) }, status: 200
  rescue => ex
    render json: { errors: ex.message }, status: 500
  end

  private
  def movie_params
    params.permit(:id, :type_reaction)
  end
end

app/controllers/api/session_controller.rb
class Api::SessionController < Api::ApplicationController
  skip_before_action :doorkeeper_authorize!, only: %i[create]
  def create
    return render json: { error: I18n.t("user.errors.invalid_client") }, status: 422 unless client_app.present?
    command = Users::CreateSession.call(user_params, client_app.id)
    render json: { result: command.result }
  rescue => ex
    render json: { errors: ex.message }, status: 500
  end

  def destroy
    revoke_token_service = Api::RevokeTokenService.new doorkeeper_token.token
    revoke_token_service.execute
    if revoke_token_service.success?
      render json: {}, status: 200
    else
      render json: {errors: revoke_token_service.errors}, status: 400
    end
  end

  private
  def user_params
    params.permit(:email, :password)
  end

  def client_app
    @client_app ||= Doorkeeper::Application.find_by(uid: params[:client_id])
  end

  def user
    @user ||= User.find_by(email: user_params[:email])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MovieApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/movies/_form.html.erb
<%= form_with(model: movie, local: true) do |form| %>
  <% if movie.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(movie.errors.count, "error") %> prohibited this movie from being saved:</h2>

      <ul>
      <% movie.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :url %>
    <%= form.text_field :url %>
  </div>

  <div class="field">
    <%= form.label :total_liked %>
    <%= form.number_field :total_liked %>
  </div>

  <div class="field">
    <%= form.label :total_disliked %>
    <%= form.number_field :total_disliked %>
  </div>

  <div class="field">
    <%= form.label :shared_by %>
    <%= form.text_field :shared_by %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/movies/edit.html.erb
<h1>Editing Movie</h1>

<%= render 'form', movie: @movie %>

<%= link_to 'Show', @movie %> |
<%= link_to 'Back', movies_path %>

app/views/movies/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Movies</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Url</th>
      <th>Total liked</th>
      <th>Total disliked</th>
      <th>Shared by</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @movies.each do |movie| %>
      <tr>
        <td><%= movie.title %></td>
        <td><%= movie.url %></td>
        <td><%= movie.total_liked %></td>
        <td><%= movie.total_disliked %></td>
        <td><%= movie.shared_by %></td>
        <td><%= movie.description %></td>
        <td><%= link_to 'Show', movie %></td>
        <td><%= link_to 'Edit', edit_movie_path(movie) %></td>
        <td><%= link_to 'Destroy', movie, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Movie', new_movie_path %>

app/views/movies/new.html.erb
<h1>New Movie</h1>

<%= render 'form', movie: @movie %>

<%= link_to 'Back', movies_path %>

app/views/movies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @movie.title %>
</p>

<p>
  <strong>Url:</strong>
  <%= @movie.url %>
</p>

<p>
  <strong>Total liked:</strong>
  <%= @movie.total_liked %>
</p>

<p>
  <strong>Total disliked:</strong>
  <%= @movie.total_disliked %>
</p>

<p>
  <strong>Shared by:</strong>
  <%= @movie.shared_by %>
</p>

<p>
  <strong>Description:</strong>
  <%= @movie.description %>
</p>

<%= link_to 'Edit', edit_movie_path(@movie) %> |
<%= link_to 'Back', movies_path %>